import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const firaCode = Fira_Code({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} antialiased`}>
        <div className="flex flex-col justify-between min-h-dvh bg-[#0F172B] border border-[#314147] rounded-lg fira-code max-w-453 m-auto">
          <Header />
            {children}
          <footer className="w-full h-14">Footer placeholder</footer>
        </div>
      </body>
    </html>
  );
}