import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const firaCode = Fira_Code({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} antialiased`}>
        <div className="min-h-screen fira-code max-w-445 max-h-235 m-auto">
          <main className="flex justify-between border border-[#314147] rounded-lg min-h-screen w-full flex-col bg-[#0F172B] sm:items-start">
            <header className="w-full h-14">Header placeholder</header>
            {children}
            <footer className="w-full h-14">Footer placeholder</footer>
          </main>
        </div>
      </body>
    </html>
  );
}